version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3001:3000
    environment:
      - MYSQL_ROOT_PASSWORD={{$MYSQL_ROOT_PASSWORD}}}
      - MYSQL_DATABASE={{$MYSQL_DATABASE}}}
      - MYSQL_USER={{$MYSQL_USER}}}
      - MYSQL_PASSWORD={{$MYSQL_PASSWORD}}
      - MYSQL_HOST={{$MYSQL_HOST}}}
      - MYSQL_PORT={{$MYSQL_PORT}}
      - MYSQL_SCHEMA={{$MYSQL_SCHEMA}}
    depends_on:
      - db

  db:
    image: mysql:8.0.25
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD={{$MYSQL_ROOT_PASSWORD}}
      - MYSQL_DATABASE={{$MYSQL_DATABASE}}
      - MYSQL_USER={{$MYSQL_USER}}
      - MYSQL_PASSWORD={{$MYSQL_PASSWORD}}
    volumes:
      - mysqldata:/mysql/data

volumes:
  mysqldata:


